//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book.ApplicationData
{
    using System;
    using System.Collections.Generic;

    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrderItems = new HashSet<OrderItems>();
        }

        public int id { get; set; }
        public string article { get; set; }
        public string name { get; set; }
        public int unit_id { get; set; }
        public decimal price { get; set; }
        public int provider_id { get; set; }
        public int manufacturer_id { get; set; }
        public int category_id { get; set; }
        public int sale { get; set; }
        public int quantity { get; set; }
        public string description { get; set; }
        public string image_path { get; set; }

        public virtual Categories Categories { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual Providers Providers { get; set; }
        public virtual Units Units { get; set; }

        public string FullImagePath
        {
            get
            {
                string folder = System.IO.Path.Combine(
                    AppDomain.CurrentDomain.BaseDirectory,
                    "Images",
                    "ProductImage");

                string file = System.IO.Path.Combine(folder, image_path ?? "");

                if (!string.IsNullOrWhiteSpace(image_path) &&
                    System.IO.File.Exists(file))
                {
                    return file;
                }

                return System.IO.Path.Combine(folder, "picture.png");
            }
        }

        public int Count { get; set; } = 0;

        public bool BigSale => sale > 25;
        public bool IsEmpty => quantity == 0;

        public decimal NewPrice => price - (price * sale / 100);
        public bool HasSale => sale > 0;
    }
}
